### ISSUE TITLE
hashtags

### ISSUE THREAD

**Issue by BestSonny** [mharrys/phoenix-twitter#1]
@mharrys  I tested your project. It seems that the hashtag and mention function is not working. Could you give me any possible solution?

**Comment by mharrys** [comment]
Thanks for your issue. That was not good to hear. It was a while since I worked on this project, but I would start by looking in https://github.com/mharrys/phoenix-twitter/blob/master/web/static/js/app.js where the actual links for hashtags/mentions are created based on a regex. Perhaps test that regex https://github.com/mharrys/phoenix-twitter/blob/master/web/static/js/app.js#L7 and try it out in your console and see if it captures words you expect should be highlighted.

You could also look in https://github.com/mharrys/phoenix-twitter/blob/master/web/controllers/tweet_controller.ex#L72 and see if the regex captures any hashtags by a printout. You could also check the database and see if the tags are created there.

**Comment by BestSonny** [comment]
@mharrys Thank you very much. The hashtag is successfully inserted in the database. The only problem is that the current code can not translate the raw hashtag strings to links.

**Comment by mharrys** [comment]
You mean in the frontend code? Have you tried opening up your console and see if the regex in https://github.com/mharrys/phoenix-twitter/blob/master/web/static/js/app.js works? If you copy-paste the code into your console and insert some random words and hashtags etc. If I don't misunderstand you.

**Comment by BestSonny** [comment]
@mharrys I run`node web/static/js/app.js`
```javascript
(function (exports, require, module, __filename, __dirname) { import "phoenix_html"
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

**Comment by mharrys** [comment]
Oh I mean you can open up a javascript console in your browser and then you can copy and paste the relevant javascript lines.

Here is how it looks for me in Firefox Web Console. Lines without ">" is the result of the command.
```
> var tagPattern = /\S*#(?:\[[^\]]+\]|[a-zA-Z0-9]+)/;
undefined
> tagPattern.exec("#foobar");
Array [ "#foobar" ]
> tagPattern.exec("bar");
null
```

**Comment by BestSonny** [comment]
@mharrys Thank you very much. I

This is my current issue.

Put a screenshot here. Both @ and # cannot work properly.

![image](https://user-images.githubusercontent.com/6027713/33031228-a27ed2e6-cdeb-11e7-8ab8-c9e8f4bb2e68.png)

**Comment by mharrys** [comment]
Yes, I understand. There must be something wrong with the regex, at least that is my only theory. I can't reproduce it since it works for me. Is it the same if you have a longer text than just one word and test several tags and mentions?

**Comment by BestSonny** [comment]
@mharrys It reports the same issue. I'll try to figure it out.

Thank you very much.
